### ISSUE TITLE
A few comments on reading the tutorial docs.

### ISSUE THREAD

**Issue by Dunbaratu** [Toukie/KSP#1]
Some ideas that may help.

First, I am assuming that the markup is going to come later so I won't comment on that yet.  (Things like which parts are [code] and which parts are in boldface, etc).  I assume this is a first draft in raw text where you will be converting it into some kind of markup language later.

### File: "print and set":

When talking about comments:

> If you'd run these two lines of code you'd only see:
> hello world 2

It's easy for the reader who reads too fast to not notice why your word "only" is very significant and carries the entire meaning of your point, wrapped up in one simple small word.  The fact that you DO see "hello world 2" isn't the important thing here.  It's the fact that you do NOT see "hello world 1" that is important, and "mentioning by omission" (i.e. "it only does the other thing") isn't a good way to get the most important point of the example across.

To make it obvious to the reader, I'd also explicitly add this,

"But notice that you do NOT see it print
hello world 1
"

When talking about comments, I'd also mention why they exist.  It's easy for someone new to programming to think, "something you type in that literally does nothing?  Why bother?"  Maybe say something to the effect that "They're not there for the computer's sake.  The computer ignores them, but they're there to help leave explanations for the humans to see who might have to read your program."

Getting the idea across that the program is read by humans as well as the computer can help get across the idea of why comments exist.

>  don't use spaces when dealing with variables.

This is a bit unclear.  It might make someone think that while the spaces used in ``5 + 6`` are okay because it's not using variables, ``x + y`` has to be written without the spaces as ``x+y`` because you can't use spaces "when dealing with" variables.  "When dealing with" has so many possible meanings here.  You just mean the variable's can't have spaces in their names.

Grammar in this file:

In both of these:

> As you can see the hello world text doesnt exist anymore, if you'd want to print
both you could do:

> Variables don't just have to be one letter you could also use a word as a variable, don't use spaces when dealing with variables.

You are using a comma to attach two complete sentences together.

> As you can see the hello world text doesnt exist anymore

Typo: apostrophe  missing from "doesn't".

> Variables don't just have to be one letter you could also use a word as a variable

Some punctuation needed between the word "letter" and "you".  I think "you" is starting a new sentence.

### File: if

> You've probably noticed the curly brackets {}, after an if statement you don't need a period but you need these brackets.

The grammar on this feels weird.  It's like you made the phrase "after an if statement" be both the end of one sentence and that start of a second sentence at the same time.

"You've probably noticed the curly brackets {}, after an if statement"
"after an if statement you don't need a period but you need these brackets."

This example:
```
set SomeVariable to true.

if SomeVariable = true {
  print "this is true".
} else {
  print "this is false".
}
```
I'm never a fan of any test of the form "if Boolean_variable = Boolean_literal".  (``if foo = true``, and ``if foo = false`` are better expressed as just ``if foo`` and ``if not(foo)``.)  Testing if a Boolean variable is equal to a Boolean literal is sort of defeating the entire point of having Boolean variables.  There's historical reasons why testing "= true" is a bad thing in old languages that use integer numbers for Booleans (i.e. 1 is true, -1 is also true,  27 is also true.  Any non-zero is true, so which of the many kinds of true did you mean when you said "= true"), but even in modern languages that force all true Booleans to be exactly 1, it's still generally bad form to do this because "if thingy is true {" is the very definition of what "if thingy {" already means on its own.

> Back to the 'if' statement, say you're not sure if an 'if' statement will be true, you can use the 'else' statement.

That's a strange reason to want to use an `else`.  Because if you were certain the `if` would be true, you wouldn't need the `if` either.  The entire point of having an `if` is precisely because you are in a situation where you aren't sure if it will be true.  

I'd introduce it this way: "So as you have seen, we created some commands that will only happen if a condition is true, *otherwise nothing happens and we move on*.  But what if you want to do some commands when the condition is true and instead of doing *nothing* when it isn't true, you'd rather provide a second set of alternative things to do when it's false..."

### File 2.5 if else

You show an example of why not to use multiple if statements - because then you have to repeat the conditions or remember their state to get to the "leftover" cases at the bottom.  But I think there's a much better case to use - the case where you want it to do one or the other but NOT both:

```
if dist <= 1 {
  print "Distance is within a meter.".
}
If dist <= 10 {
  print "Distance is within 10 meters.".
}
if dist <= 1000 {
  print "Distance is within 1 kilometer.".
}
```
If your distance is within 1 meter, you will get all three messages, which seems redundant:
```
Distance is within a meter.
Distance is within 10 meters.
Distance is within 1 kilometer.
```
If you wanted to get one of the three messages *but not all of them*, then you use an else-if:
```
if dist <= 1 {
  print "Distance is within a meter.".
} else if dist <= 10 {
  print "Distance is within 10 meters.".
} else if dist <= 1000 {
  print "Distance is within 1 kilometer.".
} else {
  print "Distance is farther than 1 km.".
}
```

----
This is as far as I got so far (just those files - haven't gotten to the others).

**Comment by Toukie** [comment]
Incorporated feedback in the updated tutorial.
